/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serviceactivation.views;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author israelagyeman-prempeh
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form mainApp
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceOne = new javax.swing.JLabel();
        serviceTwo = new javax.swing.JLabel();
        serviceThree = new javax.swing.JLabel();
        serviceFour = new javax.swing.JLabel();
        serviceFive = new javax.swing.JLabel();
        serviceOneStart = new javax.swing.JButton();
        serviceOneStop = new javax.swing.JButton();
        serviceOneLog = new javax.swing.JButton();
        serviceTwoStart = new javax.swing.JButton();
        serviceTwoStop = new javax.swing.JButton();
        serviceTwoLog = new javax.swing.JButton();
        serviceThreeStart = new javax.swing.JButton();
        serviceThreeStop = new javax.swing.JButton();
        serviceThreeLog = new javax.swing.JButton();
        serviceFourStart = new javax.swing.JButton();
        serviceFourStop = new javax.swing.JButton();
        serviceFourLog = new javax.swing.JButton();
        serviceFiveStart = new javax.swing.JButton();
        serviceFiveStop = new javax.swing.JButton();
        serviceFiveLog = new javax.swing.JButton();
        newConnection = new javax.swing.JButton();
        serviceLabelOne = new javax.swing.JLabel();
        serviceLabelTwo = new javax.swing.JLabel();
        serviceLabelThree = new javax.swing.JLabel();
        serviceLabelFour = new javax.swing.JLabel();
        serviceLabelFive = new javax.swing.JLabel();
        bgOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysServices-Main");
        setBackground(new java.awt.Color(42, 50, 61));
        setMaximumSize(new java.awt.Dimension(600, 520));
        setMinimumSize(new java.awt.Dimension(600, 520));
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceOne.setBackground(new java.awt.Color(42, 50, 61));
        serviceOne.setForeground(new java.awt.Color(42, 50, 61));
        serviceOne.setText("Service One");
        getContentPane().add(serviceOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, 30));

        serviceTwo.setBackground(new java.awt.Color(42, 50, 61));
        serviceTwo.setForeground(new java.awt.Color(42, 50, 61));
        serviceTwo.setText("Service Two");
        getContentPane().add(serviceTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 250, 30));

        serviceThree.setBackground(new java.awt.Color(42, 50, 61));
        serviceThree.setForeground(new java.awt.Color(42, 50, 61));
        serviceThree.setText("Service Three");
        getContentPane().add(serviceThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 260, 40));

        serviceFour.setBackground(new java.awt.Color(42, 50, 61));
        serviceFour.setForeground(new java.awt.Color(42, 50, 61));
        serviceFour.setText("Service Four");
        getContentPane().add(serviceFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 260, 40));

        serviceFive.setBackground(new java.awt.Color(42, 50, 61));
        serviceFive.setForeground(new java.awt.Color(42, 50, 61));
        serviceFive.setText("Service Five");
        getContentPane().add(serviceFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 260, 30));

        serviceOneStart.setBackground(new java.awt.Color(61, 181, 145));
        serviceOneStart.setText("START");
        getContentPane().add(serviceOneStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, -1));

        serviceOneStop.setBackground(new java.awt.Color(240, 92, 85));
        serviceOneStop.setText("STOP");
        getContentPane().add(serviceOneStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        serviceOneLog.setBackground(new java.awt.Color(222, 226, 230));
        serviceOneLog.setText("LOG");
        getContentPane().add(serviceOneLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        serviceTwoStart.setBackground(new java.awt.Color(61, 181, 145));
        serviceTwoStart.setText("START");
        getContentPane().add(serviceTwoStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, -1));

        serviceTwoStop.setBackground(new java.awt.Color(240, 92, 85));
        serviceTwoStop.setText("STOP");
        getContentPane().add(serviceTwoStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        serviceTwoLog.setBackground(new java.awt.Color(222, 226, 230));
        serviceTwoLog.setText("LOG");
        getContentPane().add(serviceTwoLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        serviceThreeStart.setBackground(new java.awt.Color(61, 181, 145));
        serviceThreeStart.setText("START");
        getContentPane().add(serviceThreeStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, -1));

        serviceThreeStop.setBackground(new java.awt.Color(240, 92, 85));
        serviceThreeStop.setText("STOP");
        getContentPane().add(serviceThreeStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        serviceThreeLog.setBackground(new java.awt.Color(222, 226, 230));
        serviceThreeLog.setText("LOG");
        getContentPane().add(serviceThreeLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        serviceFourStart.setBackground(new java.awt.Color(61, 181, 145));
        serviceFourStart.setText("START");
        getContentPane().add(serviceFourStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 70, -1));

        serviceFourStop.setBackground(new java.awt.Color(240, 92, 85));
        serviceFourStop.setText("STOP");
        getContentPane().add(serviceFourStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        serviceFourLog.setBackground(new java.awt.Color(222, 226, 230));
        serviceFourLog.setText("LOG");
        getContentPane().add(serviceFourLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        serviceFiveStart.setBackground(new java.awt.Color(61, 181, 145));
        serviceFiveStart.setText("START");
        getContentPane().add(serviceFiveStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 70, -1));

        serviceFiveStop.setBackground(new java.awt.Color(240, 92, 85));
        serviceFiveStop.setText("STOP");
        getContentPane().add(serviceFiveStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        serviceFiveLog.setBackground(new java.awt.Color(222, 226, 230));
        serviceFiveLog.setText("LOG");
        getContentPane().add(serviceFiveLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        newConnection.setText("NEW CONNECTION");
        newConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(newConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 444, 210, 30));

        serviceLabelOne.setBackground(new java.awt.Color(204, 0, 0));
        serviceLabelOne.setForeground(new java.awt.Color(240, 92, 85));
        getContentPane().add(serviceLabelOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 10, 10));

        serviceLabelTwo.setBackground(new java.awt.Color(240, 92, 85));
        serviceLabelTwo.setForeground(new java.awt.Color(240, 92, 85));
        getContentPane().add(serviceLabelTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 10, 10));

        serviceLabelThree.setBackground(new java.awt.Color(240, 92, 85));
        serviceLabelThree.setForeground(new java.awt.Color(240, 92, 85));
        getContentPane().add(serviceLabelThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 10, 10));

        serviceLabelFour.setBackground(new java.awt.Color(240, 92, 85));
        serviceLabelFour.setForeground(new java.awt.Color(240, 92, 85));
        getContentPane().add(serviceLabelFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 10, 10));

        serviceLabelFive.setBackground(new java.awt.Color(240, 92, 85));
        serviceLabelFive.setForeground(new java.awt.Color(240, 92, 85));
        getContentPane().add(serviceLabelFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 10, 10));

        bgOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bg-01.png"))); // NOI18N
        bgOne.setText("bg-1");
        getContentPane().add(bgOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConnectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newConnectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainView().setVisible(true);
                
            }
        });
    }
    
    /**
     * @return JRadioButton
     * returns the radio button of the first service, to allow it to be set as running or not
     */
    public JLabel labelOne(){
        return serviceLabelOne;
    }
    
    /**
     * @return JRadioButton
     * returns the radio button of the second service, to allow it to be set as running or not
     */
    public JLabel labelTwo(){
        return serviceLabelTwo;
    }
    
    /**
     * @return JRadioButton
     * returns the radio button of the third service, to allow it to be set as running or not
     */
    public JLabel labelThree(){
        return serviceLabelThree;
    }
    
     /**
     * @return JRadioButton
     * returns the radio button of the fourth service, to allow it to be set as running or not
     */
    public JLabel labelFour(){
        return serviceLabelFour;
    }
    
     /**
     * @return JRadioButton
     * returns the radio button of the Fifth service, to allow it to be set as running or not
     */
    public JLabel labelFive(){
        return serviceLabelFive;
    }
    
    /**
     * @return JButton
     * returns start button of service one
     */
    public JButton serviceOneStart(){
        return serviceOneStart;
    }
    
    /**
     * @return JButton
     * returns stop button of service one
     */
    public JButton serviceOneStop(){
        return serviceOneStop;
    }
    
    /**
     * @return JButton
     * returns log button of service one
     */
    public JButton serviceOneLog(){
        return serviceOneLog;
    }
    
    /**
     * @return JButton
     * returns start button of service one
     */
    public JButton serviceTwoStart(){
        return serviceTwoStart;
    }
    
    /**
     * @return JButton
     * returns stop button of service one
     */
    public JButton serviceTwoStop(){
        return serviceTwoStop;
    }
    
    /**
     * @return JButton
     * returns log button of service one
     */
    public JButton serviceTwoLog(){
        return serviceTwoLog;
    }
    
    /**
     * @return JButton
     * returns start button of service one
     */
    public JButton serviceThreeStart(){
        return serviceThreeStart;
    }
    
    /**
     * @return JButton
     * returns stop button of service one
     */
    public JButton serviceThreeStop(){
        return serviceThreeStop;
    }
    
    /**
     * @return JButton
     * returns log button of service one
     */
    public JButton serviceThreeLog(){
        return serviceThreeLog;
    }
    
    /**
     * @return JButton
     * returns start button of service one
     */
    public JButton serviceFourStart(){
        return serviceFourStart;
    }
    
    /**
     * @return JButton
     * returns stop button of service one
     */
    public JButton serviceFourStop(){
        return serviceFourStop;
    }
    
    /**
     * @return JButton
     * returns log button of service one
     */
    public JButton serviceFourLog(){
        return serviceFourLog;
    }
    
    /**
     * @return JButton
     * returns start button of service one
     */
    public JButton serviceFiveStart(){
        return serviceFiveStart;
    }
    
    /**
     * @return JButton
     * returns stop button of service one
     */
    public JButton serviceFiveStop(){
        return serviceFiveStop;
    }
    
    /**
     * @return JButton
     * returns log button of service one
     */
    public JButton serviceFiveLog(){
        return serviceFiveLog;
    }
    
    /**
     * @return JButton
     * returns a button to create a new connection
     */
    public JButton newConnectionBtn(){
        return newConnection;
    }
    
    public void setAllToRed(){
        labelOne().setOpaque(true);
        labelOne().setBackground(Color.red);
        labelTwo().setOpaque(true);
        labelTwo().setBackground(Color.red);
        labelThree().setOpaque(true);
        labelThree().setBackground(Color.red);
        labelFour().setOpaque(true);
        labelFour().setBackground(Color.red);
        labelFive().setOpaque(true);
        labelFive().setBackground(Color.red);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgOne;
    private javax.swing.JButton newConnection;
    private javax.swing.JLabel serviceFive;
    private javax.swing.JButton serviceFiveLog;
    private javax.swing.JButton serviceFiveStart;
    private javax.swing.JButton serviceFiveStop;
    private javax.swing.JLabel serviceFour;
    private javax.swing.JButton serviceFourLog;
    private javax.swing.JButton serviceFourStart;
    private javax.swing.JButton serviceFourStop;
    private javax.swing.JLabel serviceLabelFive;
    private javax.swing.JLabel serviceLabelFour;
    private javax.swing.JLabel serviceLabelOne;
    private javax.swing.JLabel serviceLabelThree;
    private javax.swing.JLabel serviceLabelTwo;
    private javax.swing.JLabel serviceOne;
    private javax.swing.JButton serviceOneLog;
    private javax.swing.JButton serviceOneStart;
    private javax.swing.JButton serviceOneStop;
    private javax.swing.JLabel serviceThree;
    private javax.swing.JButton serviceThreeLog;
    private javax.swing.JButton serviceThreeStart;
    private javax.swing.JButton serviceThreeStop;
    private javax.swing.JLabel serviceTwo;
    private javax.swing.JButton serviceTwoLog;
    private javax.swing.JButton serviceTwoStart;
    private javax.swing.JButton serviceTwoStop;
    // End of variables declaration//GEN-END:variables
}
